<?php
declare(strict_types=1);

use App\View\ExceptionView;
use function Miklcct\ThinPhpApp\Escaper\xml;

/** @var ExceptionView $this */
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>An error occurred</title>
    </head>
    <body>
        <h1>Oops, an error has been occurred!</h1>
        <h2>Details</h2>
        <p><code><?= xml($this->exception->getFile() . ':' . $this->exception->getLine() . ': ' . $this->exception->getMessage()) ?></code></p>
        <h3>Stack trace</h3>
        <pre><?= xml($this->exception->getTraceAsString()) ?></pre>
    </body>
</html>
