<?php
declare(strict_types=1);

use App\View\HelloView;
use function Miklcct\ThinPhpApp\Escaper\xml;

/** @var HelloView $this */

?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Hello</title>
    </head>
    <body>
        <p>
            Hello World!
        </p>
        <p>
            The server time now is <?= xml(strftime('%c')) ?>.
        </p>
        <p>
            The URL of this page is <a href="<?= xml($this->url) ?>"><?= xml($this->url) ?></a>.
        </p>
        <p>
            You are visiting this page from IP address <?= xml($this->ipAddress) ?>.
        </p>
        <ul>
            <li>
                <a href="animation.php">Animation example using XHTML + SVG</a>
            </li>
        </ul>
    </body>
</html>