<?php
declare(strict_types=1);

use App\View\HelloView;
use function Miklcct\ThinPhpApp\e;

/** @var HelloView $this */

?>
<!DOCTYPE html>
<html>
    <head>
        <title>Hello</title>
    </head>
    <body>
        <p>
            Hello World!
        </p>
        <p>
            The server time now is <?= e(strftime('%c')) ?>.
        </p>
        <p>
            The URL of this page is <a href="<?= e($this->url) ?>"><?= e($this->url) ?></a>.
        </p>
        <p>
            You are visiting this page from IP address <?= e($this->ipAddress) ?>.
        </p>
    </body>
</html>